import os

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

ASSETS_FOLDER = os.path.join(PROJECT_ROOT, "assets")
ASSETS_CONTRACTS_FOLDER = os.path.join(ASSETS_FOLDER, "contracts")
ASSETS_TEXT_FOLDER = os.path.join(ASSETS_FOLDER, "text")

DATA_FOLDER = os.path.join(PROJECT_ROOT, "data")
DATA_STUDENTS_FOLDER = os.path.join(DATA_FOLDER, "students")
DATA_CHECKINS_FOLDER = os.path.join(DATA_FOLDER, "checkins")
DATA_PHOTOS_FOLDER = os.path.join(DATA_FOLDER, "photos")
DATA_PHOTOS_CHECKINS_FOLDER = os.path.join(DATA_PHOTOS_FOLDER, "checkins")
DATA_CONTRACTS_FOLDER = os.path.join(DATA_FOLDER, "contracts")
DATA_CONTRACTS_SIGNED_FOLDER = os.path.join(DATA_CONTRACTS_FOLDER, "signed")

DATABASE_FILE = os.path.join(DATA_STUDENTS_FOLDER, "database.csv")
BEHAVIORAL_CONTRACT_TEMPLATE = os.path.join(
    ASSETS_CONTRACTS_FOLDER,
    "Robotics Lab Behavioral Contract 2026.pdf"
)
BEHAVIORAL_CONTRACT_SIGNED_FOLDER = DATA_CONTRACTS_SIGNED_FOLDER
TERMS_FILE = os.path.join(ASSETS_TEXT_FOLDER, "terms_and_conditions.txt")
RUNTIME_DIRECTORIES = (
    DATA_STUDENTS_FOLDER,
    DATA_CHECKINS_FOLDER,
    DATA_PHOTOS_CHECKINS_FOLDER,
    DATA_CONTRACTS_SIGNED_FOLDER,
)

ADMIN_USERNAME = "admin" # PLEASE CHANGE (Look in "System Info" file)
ADMIN_PASSWORD = "admin1234" # PLEASE CHANGE (Look in "System Info" file)

APP_BACKGROUND_COLOR = "#eef2f6"
PANEL_BACKGROUND_COLOR = "#ffffff"
PANEL_BORDER_COLOR = "#d5dde6"
PRIMARY_TEXT_COLOR = "#182533"
SECONDARY_TEXT_COLOR = "#5d6b78"
ACCENT_TEXT_COLOR = "#274c77"
STATUS_BACKGROUND_COLOR = "#f7f9fb"
INPUT_BACKGROUND_COLOR = "#ffffff"

TITLE_FONT = ("Arial", 30, "bold")
SCREEN_TITLE_FONT = ("Arial", 24, "bold")
INSTRUCTION_FONT = ("Arial", 18)
BODY_FONT = ("Arial", 16)
MESSAGE_FONT = ("Arial", 18, "bold")
DETAIL_FONT = ("Arial", 14)
INPUT_FONT = ("Arial", 20)
BUTTON_FONT = ("Arial", 16, "bold")
SMALL_FONT = ("Arial", 12)

KIOSK_FULLSCREEN = True
KIOSK_LOCK_KEYS = True
KIOSK_ALLOW_ESC_EXIT = False
KIOSK_FORCE_NUMLOCK = True
KIOSK_KEY_LOCK_RETRY_DELAYS_SEC = [5, 10, 20]

# Capture tuning
BUFFER_DURATION_SEC = 2.5
PRE_EVENT_WINDOW_SEC = 0.3
POST_EVENT_WINDOW_SEC = 1.6
FRAME_SAMPLE_INTERVAL_MS = 200
FACE_DETECT_SCALE = 0.5
MIN_FACE_SIZE_RATIO = 0.055
CENTER_TOLERANCE_RATIO = 0.16
BLUR_THRESHOLD = 60.0
BRIGHTNESS_MIN = 80.0
BRIGHTNESS_MAX = 175.0
MAX_BUFFER_FRAMES = 18
PREFERRED_POST_EVENT_SEC = 0.35
CLEAR_FACE_CENTER_SCORE = 0.55
CLEAR_FACE_EDGE_SCORE = 0.4
DEBUG_SAVE_FRAMES = False

STATUS_MESSAGE_TIMEOUT_MS = 3000
CAMERA_INDEX_MIN = 0
CAMERA_INDEX_MAX = 5
CAMERA_DISCOVERY_RETRY_SEC = 3.0
CAMERA_PROBE_WARMUP_SEC = 0.35
CAMERA_PROBE_ATTEMPTS = 4
CAMERA_PROBE_READ_INTERVAL_SEC = 0.1
CAMERA_READ_FAILURE_LIMIT = 12

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 550
